'use client';
import {useEffect,useState} from 'react';
import HeroSlideshow from './HeroSlideshow';
import {assess,frames,fields} from '../lib/rules.mjs';
import {retail} from '../lib/pricing.mjs';
const money=amount=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(amount);
const steps=['Your window','Your fit','Measure','Your style','Review'];
const blank={name:'Living room',frame:'z',depth:'',obstructions:'unsure',tiltIn:'unsure',sill:'unsure',color:'Pure White',louver:'3.5',panels:'2',hinge:'left',tilt:'center',rail:'adjust',alignment:'no',notes:'',...Object.fromEntries(fields.map(f=>[f,'']))};
const fractions=['0','1/16','1/8','3/16','1/4','5/16','3/8','7/16','1/2','9/16','5/8','11/16','3/4','13/16','7/8','15/16'];
const measureGroups=[fields.slice(0,3),fields.slice(3,6),fields.slice(6,8)];
function inches(value){const ticks=Math.round(Number(value)*16);return `${Math.floor(ticks/16)}${ticks%16?' '+fractions[ticks%16]:''}″`}
function MeasureDiagram({part}){return <svg className="measure-diagram" viewBox="0 0 360 280" role="img" aria-label={['Measure across the opening at top, middle, and bottom.','Measure the opening height at left, center, and right.','Measure corner to corner in both directions.'][part]}><rect x="45" y="30" width="270" height="220" fill="#f8faf5" stroke="#203c36" strokeWidth="4"/><g stroke="#a54c2c" strokeWidth="2" fill="#a54c2c">{part===0&&[60,140,220].map((y,i)=><g key={y}><path d={`M47 ${y}H313 M47 ${y-5}V${y+5} M313 ${y-5}V${y+5}`}/><text x="180" y={y-9} textAnchor="middle" stroke="none" fontSize="15">{['Top','Middle','Bottom'][i]}</text></g>)}{part===1&&[80,180,280].map((x,i)=><g key={x}><path d={`M${x} 32V248 M${x-5} 32H${x+5} M${x-5} 248H${x+5}`}/><text x={x} y="20" textAnchor="middle" stroke="none" fontSize="15">{['Left','Center','Right'][i]}</text></g>)}{part===2&&<><path d="M47 32L313 248"/><path d="M313 32L47 248" strokeDasharray="6 5"/><text x="65" y="65" stroke="none" fontSize="16">1</text><text x="285" y="65" stroke="none" fontSize="16">2</text></>}</g></svg>}
const labels=['Width · top','Width · middle','Width · bottom','Height · left','Height · center','Height · right','Diagonal · top left to bottom right','Diagonal · top right to bottom left'];
function Choice({value,onChange,options}){return <div className="choices">{options.map(o=><button key={o.value} type="button" aria-pressed={value===o.value} className={'choice '+(value===o.value?'selected':'')} onClick={()=>onChange(o.value)}><span className="radio"/><span><strong>{o.label}</strong>{o.detail&&<small>{o.detail}</small>}</span></button>)}</div>}
function Shutter({w,measure=false}){const ys=Array.from({length:13},(_,i)=>67+i*18);return <svg viewBox="0 0 340 370" role="img" aria-label={measure?'Window measuring diagram: three widths, three heights, and two diagonals.':'Illustrative two-panel shutter; factory rail and louver layout may differ.'}><rect x="52" y="40" width="236" height="290" fill="#ecefeb" stroke="#203c36" strokeWidth="3"/><rect x="66" y="54" width="208" height="262" fill="#fbfcf9" stroke="#85968e"/>{measure?<g stroke="#a54c2c" fill="#a54c2c" fontSize="12"><path d="M70 70H270 M70 180H270 M70 300H270 M80 60V310 M170 60V310 M260 60V310" strokeDasharray="4 4"/><path d="M66 54L274 316 M274 54L66 316" opacity=".45"/><text x="137" y="31" stroke="none">TOP WIDTH</text><text x="122" y="350" stroke="none">BOTTOM WIDTH</text><text x="120" y="174" stroke="none">MIDDLE WIDTH</text></g>:<g>{ys.map(y=><path key={y} d={`M70 ${y}H270`} stroke="#b4beb4" strokeWidth="3"/>)}{w.panels==='2'&&<rect x="164" y="54" width="12" height="262" fill="#f4f5f0" stroke="#85968e"/>}{w.tilt==='center'&&<><rect x={w.panels==='2'?110:167} y="65" width="5" height="240" fill="#dddcd1"/>{w.panels==='2'&&<rect x="221" y="65" width="5" height="240" fill="#dddcd1"/>}</>}{Number(w.heightCenter)>74&&<rect x="66" y="179" width="208" height="15" fill="#deded4"/>}</g>}</svg>}
export default function Page(){const [started,start]=useState(false),[step,setStep]=useState(0),[measurePart,setMeasurePart]=useState(0),[w,setW]=useState(blank),[ready,setReady]=useState(false),[photo,setPhoto]=useState(''),[notice,setNotice]=useState(''),[help,setHelp]=useState(false),[fileError,setFileError]=useState('');
 useEffect(()=>{try{const d=JSON.parse(localStorage.getItem('shutter-demo-v1'));if(d?.window)setW({...blank,...d.window})}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('shutter-demo-v1',JSON.stringify({window:w}))}catch{}},[w,ready]);
 const update=(k,v)=>setW(p=>({...p,[k]:v})),result=assess(w);
 const moveTo=(next)=>{setNotice('');setStep(next);window.scrollTo({top:0,behavior:'smooth'})};
 const advance=()=>{
  if(step===2){
   if(measurePart<3){const valid=measureGroups[measurePart].every(f=>String(w[f]??'').trim()!==''&&Number.isFinite(Number(w[f]))&&Number(w[f])>0&&Number(w[f])<=300);if(!valid){setNotice('Enter each measurement in inches before continuing.');return}setNotice('');setMeasurePart(measurePart+1);window.scrollTo({top:0,behavior:'smooth'});return}
   if(!result.valid){setNotice('Please check your measurements.');return}
  }
  if(step===1)setMeasurePart(0);
  moveTo(Math.min(4,step+1));
 };
 const back=()=>{if(step===2&&measurePart>0){setMeasurePart(measurePart-1);setNotice('');window.scrollTo({top:0,behavior:'smooth'})}else{if(step===3)setMeasurePart(3);moveTo(step-1)}};
 const download=()=>{const data={project:'Woodlore Americas preview',status:'Demonstration only — not an order or approved manufacturing specification',window:w,assessment:result,pricing:`Base ${money(retail.basePerSquareFoot)} per billable sq. ft.; InvisibleTilt ${money(retail.invisibleTiltPerPanel)} per panel. Selected upgrade included. Shipping and tax excluded.`};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='my-shutter-plan.json';a.click();URL.revokeObjectURL(url);setNotice('Your plan was downloaded. Nothing has been submitted or ordered.')};
 return <><div className="preview">WORKING PREVIEW <span>Preview · No payments or orders</span></div><header><a href="/" className="brand">SHUTTER<span>STUDIO</span><small>Working name</small></a><button className="textbutton" onClick={()=>setHelp(true)}>Need a hand? <span>↗</span></button></header>
 {!started?<main className="landing"><div className="hero-copy"><p className="eyebrow">NORMAN WOODLORE AMERICAS</p><h1>Your windows.<br/>A beautiful fit.</h1><p className="lede">Custom composite shutters in classic whites. We’ll walk you through the fit, measurements, and finishing touches—one window at a time.</p><button className="primary" onClick={()=>start(true)}>Build my shutters <span>→</span></button><p className="micro">No account needed. Your progress stays in this browser.</p><div className="pill-row"><span>Made in Mexico</span><span>Custom dimensions</span><span>Expert review before production</span></div></div><HeroSlideshow/><section className="intro-strip"><div><b>01</b><h3>Find your fit</h3><p>A few questions about your window.</p></div><div><b>02</b><h3>Make it yours</h3><p>White finishes. Clear, visual choices.</p></div><div><b>03</b><h3>Check every detail</h3><p>Review your plan before the next step.</p></div></section></main>:<main className="builder"><div className="builder-top"><button className="textbutton" onClick={()=>start(false)}>← Back to overview</button><span>One-window demonstration</span></div><nav className="steps" aria-label="Configuration progress">{steps.map((s,i)=><button key={s} disabled={i>step} aria-current={i===step?'step':undefined} className={i===step?'active':i<step?'done':''} onClick={()=>{if(i===2)setMeasurePart(0);moveTo(i)}}><b>{i+1}</b><span>{s}</span></button>)}</nav><div className={'builder-grid '+(step===2?'measuring':'')}><section className="form-panel"><p className="eyebrow">STEP {step+1} OF 5</p>
 {step===0&&<><h1>Let’s meet your window.</h1><p className="lede">Start with one opening. A few details help us spot anything that needs a closer look.</p><label className="field">Give this window a name<input maxLength={80} value={w.name} onChange={e=>update('name',e.target.value)} placeholder="For example, kitchen sink"/></label><div className="upload"><label htmlFor="photo">Add a window photo <span>Optional for this demonstration</span></label><input id="photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>8e6){setFileError('Choose a JPG, PNG, or WebP under 8 MB.');return}setFileError('');const r=new FileReader();r.onload=()=>setPhoto(r.result);r.readAsDataURL(f)}}/>{photo&&<img src={photo} alt="Your selected window"/>}<small>Show the full opening, surrounding trim, and sill. Photo stays on this screen; it is not uploaded or saved.</small>{fileError&&<p role="alert">{fileError}</p>}</div>{[['obstructions','Any cranks, locks, alarm sensors, or other obstructions?'],['tiltIn','Do your windows tilt inward for cleaning?'],['sill','Is there a projecting bottom sill?']].map(([k,q])=><fieldset key={k}><legend>{q}</legend><Choice value={w[k]} onChange={v=>update(k,v)} options={[{value:'no',label:'No'},{value:'yes',label:'Yes'},{value:'unsure',label:'Not sure'}]}/></fieldset>)}</>}
 {step===1&&<><h1>Choose how it fits.</h1><p className="lede">Think about your existing trim and the space around the opening. We’ll review the final mounting details.</p><Choice value={w.frame} onChange={v=>update('frame',v)} options={[{value:'z',label:'Inside mount · Z-frame',detail:'Fits within the opening, with a lip overlapping the edge.'},{value:'l',label:'Outside mount · L-frame',detail:'Mounts around the opening. Needs a suitable, clear mounting surface.'},{value:'hang',label:'Inside mount · Hangstrip',detail:'Mounts behind the panels. Clearance must be checked before ordering.'}]}/><label className="field">Window opening depth (inches)<input type="number" step="0.0625" min="0" value={w.depth} onChange={e=>update('depth',e.target.value)} placeholder="For example, 3.5"/><small>Measure from the front edge of the opening to the nearest obstruction at the proposed mounting location. Leave blank if unsure.</small></label><div className="note">Depth alone does not confirm fit. The frame, louver rotation, bottom support, and window hardware all need to work together.</div><label className="field">Anything we should know?<textarea rows="3" maxLength={1500} value={w.notes} onChange={e=>update('notes',e.target.value)} placeholder="Tell us about trim, handles, clearance, or questions."/></label></>}
 {step===2&&<><p className="measure-progress">{['Width','Height','Diagonals','Summary'].map((title,i)=><span key={title} aria-current={measurePart===i?'step':undefined} className={measurePart===i?'current':''}>{title}{i<3&&<span className="progress-divider"> / </span>}</span>)}</p>
 <h1>{['Let’s measure the width.','Now, the height.','Check the opening.','Your opening measurements.'][measurePart]}</h1>
 {measurePart<3?<><p className="lede">{['Measure across the opening at the top, middle, and bottom.','Measure from top to bottom at the left, center, and right.','Measure diagonally from corner to corner in both directions.'][measurePart]}</p><div className="measurement-work"><MeasureDiagram part={measurePart}/><div className="measure-inputs">{measureGroups[measurePart].map(f=>{const i=fields.indexOf(f),n=Number(w[f]||0),whole=Math.floor(n),fraction=Math.round((n-whole)*16);return <label className="field" key={f}>{labels[i]}<div className="fraction"><input aria-label={labels[i]+' whole inches'} type="number" min="0" max="300" step="1" placeholder="Inches" value={w[f]===''?'':whole} onChange={e=>update(f,e.target.value===''?'':String(Math.max(0,Math.floor(Number(e.target.value)))+fraction/16))}/><select aria-label={labels[i]+' fraction of an inch'} value={fraction} onChange={e=>update(f,String(whole+Number(e.target.value)/16))}>{fractions.map((label,j)=><option key={j} value={j}>{label}″</option>)}</select></div></label>})}</div></div><p className="measure-tip">Measure the opening itself at the same mounting plane. Don’t add or subtract allowances.</p></>:<><p className="lede">{w.frame==='l'?'Largest measurements used for outside mount.':'Smallest measurements used for inside mount.'}</p>{result.valid?<><div className="opening-result"><div><span>Width</span><strong>{inches(result.width)}</strong></div><span className="times">×</span><div><span>Height</span><strong>{inches(result.height)}</strong></div></div><p className="measure-tip">Opening measurements—not the final manufactured shutter size.</p>{result.flags.some(f=>/varies|diagonal/i.test(f))&&<div className="review-flags" role="status"><h3>These measurements need a fit check.</h3><ul>{result.flags.filter(f=>/varies|diagonal/i.test(f)).map(f=><li key={f}>{f}</li>)}</ul><p>We’ll review the opening with you before production. Outside mount may be an option.</p></div>}</>:<p className="flag">Please check that all eight measurements are complete.</p>}<div className="measurement-details">{measureGroups.map((group,i)=><div key={i}><div className="measurement-detail-heading"><h3>{['Widths','Heights','Diagonals'][i]}</h3><button className="textbutton" onClick={()=>{setMeasurePart(i);setNotice('')}}>Edit {['widths','heights','diagonals'][i]}</button></div>{group.map(f=><div className="measurement-value" key={f}><span>{labels[fields.indexOf(f)]}</span><strong>{w[f]?inches(w[f]):'Not entered'}</strong></div>)}</div>)}</div></>}
 </>}
 {step===3&&<><h1>The finishing touches.</h1><p className="lede">A few choices make it yours. The illustration is a guide, not a manufacturing drawing.</p><fieldset><legend>Your white</legend><div className="swatches">{['Pure White','Extra White','Silk White',"Decorator’s White"].map((c,i)=><button aria-pressed={w.color===c} className={w.color===c?'selected':''} key={c} onClick={()=>update('color',c)}><span style={{background:['#fff','#f5f5f0','#f4f0e3','#ecebe5'][i]}}/>{c}</button>)}</div><small>Screen colors are approximate. Check a physical sample before ordering.</small></fieldset><fieldset><legend>Louver size</legend><Choice value={w.louver} onChange={v=>update('louver',v)} options={[{value:'3.5',label:'3½ inches'},{value:'4.5',label:'4½ inches'}]}/></fieldset><fieldset><legend>Panel arrangement</legend><Choice value={w.panels} onChange={v=>update('panels',v)} options={[{value:'1',label:'One panel'},{value:'2',label:'Two panels',detail:'Open from the center'}]}/>{w.panels==='1'&&<Choice value={w.hinge} onChange={v=>update('hinge',v)} options={[{value:'left',label:'Hinges on left'},{value:'right',label:'Hinges on right'}]}/>}</fieldset><fieldset><legend>Louver control</legend><Choice value={w.tilt} onChange={v=>update('tilt',v)} options={[{value:'center',label:'Traditional center rod',detail:'Included'},{value:'invisible',label:'InvisibleTilt',detail:`+${money(retail.invisibleTiltPerPanel)} per panel. Taller panels may have separate operating sections.`}]}/></fieldset>{Math.max(Number(w.heightLeft),Number(w.heightCenter),Number(w.heightRight))>74&&<fieldset><legend>Divider rail planning</legend><p>This opening may require a divider rail. The requirement applies to finished panels over 74″ tall; final panel height will be checked.</p><Choice value={w.rail} onChange={v=>update('rail',v)} options={[{value:'adjust',label:'Centered, adjustment allowed',detail:`Allows up to ${w.louver==='3.5'?'±1½″':'±2″'} movement under the supplied divider-rail specification to balance the rails.`},{value:'exact',label:'Exactly centered',detail:'Top and bottom rails may be different heights. Final dimensions require approval.'}]}/></fieldset>}<fieldset><legend>Must rails align with another window or feature?</legend><Choice value={w.alignment} onChange={v=>update('alignment',v)} options={[{value:'no',label:'No'},{value:'yes',label:'Yes · please review'}]}/></fieldset></>}
 {step===4&&<><h1>Your window, considered.</h1><p className="lede">Here’s your saved plan. This demonstration does not submit an order or take payment.</p><dl className="summary">{[['Window',w.name],['Mount',frames[w.frame].name],['Frame',frames[w.frame].detail],['Opening measurements',`${inches(result.width)} × ${inches(result.height)}`],['Finish',w.color],['Louvers',w.louver+'″'],['Panels',w.panels==='2'?'Two · center opening':`One · ${w.hinge} hinged`],['Tilt',w.tilt==='center'?'Center rod':'InvisibleTilt'],['Billable area',result.area?.toFixed(2)+' sq. ft.'],['Base shutter',money(result.pricing?.base)],...(w.tilt==='invisible'?[['InvisibleTilt upgrade',money(result.pricing?.invisibleTilt)]]:[]),['Estimated shutter total',money(result.estimate)]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><div className="note"><b>Every plan receives a final fit check.</b><p>Frame deductions, panel dimensions, support, clearance, and factory rounding are not yet approved manufacturing specifications.</p></div>{result.flags.length>0&&<div className="review-flags"><h3>Details to discuss</h3><ul>{result.flags.map(f=><li key={f}>{f}</li>)}</ul></div>}<button className="primary" onClick={download}>Download my plan <span>↓</span></button><p className="micro">Saved to your device. No email or production request is sent.</p></>}
 {notice&&<p role="status" className="flag">{notice}</p>}<div className="form-footer">{step>0&&<button className="secondary" onClick={back}>← Back</button>}{step<4&&<button className="primary" onClick={advance}>{step===2?['Continue to height','Check diagonals','See my measurements','Choose my style'][measurePart]:'Continue'} <span>→</span></button>}</div></section>{step!==2&&<aside><div className="preview-card"><p className="eyebrow">{w.name||'YOUR WINDOW'}</p><Shutter w={w} measure={step===2}/><h3>Woodlore Americas</h3><p>{w.color} · Composite shutters</p><div className="price"><span>Estimated shutter total</span><strong>{result.valid?money(result.estimate):'Measure to estimate'}</strong></div>{result.valid&&<dl className="summary"><div><dt>Base shutter</dt><dd>{money(result.pricing.base)}</dd></div>{w.tilt==='invisible'&&<div><dt>InvisibleTilt · {w.panels} {w.panels==='1'?'panel':'panels'}</dt><dd>+{money(result.pricing.invisibleTilt)}</dd></div>}</dl>}<small>{money(retail.basePerSquareFoot)}/sq. ft., 8 sq. ft. minimum. Selected InvisibleTilt is included in the total. Shipping and tax are additional. Final configuration subject to review.</small></div><p className="aside-note">Your measurements stay editable. Nothing goes into production from this preview.</p></aside>}</div></main>}
 <footer><span>Shutter Studio · Working demonstration</span><span>Norman Woodlore Americas · Independent storefront concept</span></footer>{help&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="help-title" className="modal"><button autoFocus className="textbutton" onClick={()=>setHelp(false)}>Close ×</button><h2 id="help-title">A little help with the fit.</h2><p>For this demonstration, add your question in the notes under “Your fit.” Your downloaded plan will include it.</p><p>Live phone, email, and photo submission will be connected before launch. Nothing is being sent yet.</p><button className="primary" onClick={()=>{start(true);setStep(1);setHelp(false)}}>Add a question →</button></section></div>}</>;
}
